[Metadata]
Name=jade
Version=0.1
Author=nate zhou
Description=Simple dark theme.

[InputPanel]
EnableBlur=False
NormalColor=#eeeeee
HighlightCandidateColor=#ffffff
HighlightColor=#111111
HighlightBackgroundColor=#111111
Spacing=0

[InputPanel/Highlight]
Color=#427b58

[InputPanel/Background]
Color=#111111

[InputPanel/ContentMargin]
Left=6
Right=6
Top=0
Bottom=0

[InputPanel/TextMargin]
Left=6
Right=6
Top=0
Bottom=0

[InputPanel/Background/Margin]
Left=6
Right=6
Top=0
Bottom=0

[InputPanel/Highlight/Margin]
Left=6
Right=6
Top=0
Bottom=0

[InputPanel/PrevPage/ClickMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/NextPage/ClickMargin]
Left=0
Right=0
Top=0
Bottom=0
